:: Obsolete
::powershell -ExecutionPolicy Bypass -File build_whdload_screenshots_new.ps1 -screenshotQueriesFile "demos_screenshot_data\aeb_whdload_demos_screenshots_queries.csv" -screenshotSourcesFile "demos_screenshot_data\demos_screenshot_sources.csv" -outputPath "screenshots\aeb_whdload_demos"
::powershell -ExecutionPolicy Bypass -File build_whdload_screenshots_new.ps1 -screenshotQueriesFile "demos_screenshot_data\aeb_whdload_demos_aga_screenshots_queries.csv" -screenshotSourcesFile "demos_screenshot_data\demos_screenshot_sources.csv" -outputPath "screenshots\aeb_whdload_demos_aga"
::powershell -ExecutionPolicy Bypass -File build_whdload_screenshots_new.ps1 -screenshotQueriesFile "games_screenshot_data\aeb_whdload_games_screenshots_queries.csv" -screenshotSourcesFile "games_screenshot_data\games_screenshot_sources.csv" -outputPath "screenshots\aeb_whdload_games" -minScore 1
::powershell -ExecutionPolicy Bypass -File build_whdload_screenshots_new.ps1 -screenshotQueriesFile "games_screenshot_data\aeb_whdload_games_aga_screenshots_queries.csv" -screenshotSourcesFile "games_screenshot_data\games_screenshot_sources.csv" -outputPath "screenshots\aeb_whdload_games_aga" -minScore 1
::powershell -ExecutionPolicy Bypass -File build_whdload_screenshots_new.ps1 -screenshotQueriesFile "games_screenshot_data\aeb_whdload_games_cd32_screenshots_queries.csv" -screenshotSourcesFile "games_screenshot_data\games_screenshot_sources.csv" -outputPath "screenshots\aeb_whdload_games_cd32" -minScore 1

:: Demos
powershell -ExecutionPolicy Bypass -File build_whdload_screenshots_new.ps1 -screenshotQueriesFile "demos_screenshot_data\aeb_whdload_demos_ocs_screenshots_queries.csv" -screenshotSourcesFile "demos_screenshot_data\demos_screenshot_sources.csv" -outputPath "screenshots\aeb_whdload_demos_ocs" -noConvertScreenshots
powershell -ExecutionPolicy Bypass -File build_whdload_screenshots_new.ps1 -screenshotQueriesFile "demos_screenshot_data\aeb_whdload_demos_aga_screenshots_queries.csv" -screenshotSourcesFile "demos_screenshot_data\demos_screenshot_sources.csv" -outputPath "screenshots\aeb_whdload_demos_aga" -noConvertScreenshots

:: Games
powershell -ExecutionPolicy Bypass -File build_whdload_screenshots_new.ps1 -screenshotQueriesFile "games_screenshot_data\aeb_whdload_games_ocs_screenshots_queries.csv" -screenshotSourcesFile "games_screenshot_data\games_screenshot_sources.csv" -outputPath "screenshots\aeb_whdload_games_ocs" -minScore 1 -noConvertScreenshots
powershell -ExecutionPolicy Bypass -File build_whdload_screenshots_new.ps1 -screenshotQueriesFile "games_screenshot_data\aeb_whdload_games_aga_screenshots_queries.csv" -screenshotSourcesFile "games_screenshot_data\games_screenshot_sources.csv" -outputPath "screenshots\aeb_whdload_games_aga" -minScore 1 -noConvertScreenshots