powershell -ExecutionPolicy Bypass -File build_whdload_index.ps1 -whdloadArchiveFilesPath whdownload_games whdownload_games_slave_index
powershell -ExecutionPolicy Bypass -File build_whdload_index.ps1 -whdloadArchiveFilesPath whdload_installs\installs whdload_installs_slave_index
