:: Demos
powershell -ExecutionPolicy Bypass -File build_whdload_queries.ps1 -entriesFiles "data\eab_whdload_packs_3.0\filtered\Demos_WHDLoad_filtered.csv,data\eab_whdload_packs_3.0\filtered\Demos_WHDLoad_UnpackOnAmiga_filtered.csv" -queryPatchesFile "data\eab_whdload_packs_3.0\screenshots\demos_screenshot_query_patches.csv" -queriesFile "data\eab_whdload_packs_3.0\screenshots\demos_screenshot_queries.csv" -addWhdloadSlaveName -addWhdloadSlaveCopy
powershell -ExecutionPolicy Bypass -File build_whdload_queries.ps1 -entriesFiles "data\eab_whdload_packs_3.0\filtered\Demos_WHDLoad_filtered.csv,data\eab_whdload_packs_3.0\filtered\Demos_WHDLoad_UnpackOnAmiga_filtered.csv" -queryPatchesFile "data\eab_whdload_packs_3.0\details\demos_detail_query_patches.csv" -queriesFile "data\eab_whdload_packs_3.0\details\demos_detail_queries.csv" -addWhdloadSlaveName -addWhdloadSlaveCopy

:: Games
powershell -ExecutionPolicy Bypass -File build_whdload_queries.ps1 -entriesFiles "data\eab_whdload_packs_3.0\filtered\Games_WHDLoad_filtered.csv,data\eab_whdload_packs_3.0\filtered\Games_WHDLoad_AGA_filtered.csv,data\eab_whdload_packs_3.0\filtered\Games_WHDLoad_UnpackOnAmiga_filtered.csv" -queryPatchesFile "data\eab_whdload_packs_3.0\screenshots\games_screenshot_query_patches.csv" -queriesFile "data\eab_whdload_packs_3.0\screenshots\games_screenshot_queries.csv" -noWhdloadName -addFilteredName -addWhdloadSlaveName -removeQueryWordsPattern "^(Demo|Disk|OCS|ECS|AGA|CDTV|CD32)$"
powershell -ExecutionPolicy Bypass -File build_whdload_queries.ps1 -entriesFiles "data\eab_whdload_packs_3.0\filtered\Games_WHDLoad_filtered.csv,data\eab_whdload_packs_3.0\filtered\Games_WHDLoad_AGA_filtered.csv,data\eab_whdload_packs_3.0\filtered\Games_WHDLoad_UnpackOnAmiga_filtered.csv" -queryPatchesFile "data\eab_whdload_packs_3.0\details\games_detail_query_patches.csv" -queriesFile "data\eab_whdload_packs_3.0\details\games_detail_queries.csv" -noWhdloadName -addFilteredName -addWhdloadSlaveName -removeQueryWordsPattern "^(Demo|Disk|OCS|ECS|AGA|CDTV|CD32)$"

:: HD-Games
powershell -ExecutionPolicy Bypass -File build_whdload_queries.ps1 -entriesFiles "data\hd-games\entries\hd-games_entries.csv" -queryPatchesFile "data\hd-games\screenshots\hd-games_screenshot_query_patches.csv" -queriesFile "data\hd-games\screenshots\hd-games_screenshot_queries.csv" -addFilteredName -removeQueryWordsPattern "^(Demo|Disk|OCS|ECS|AGA|CDTV|CD32)$"
powershell -ExecutionPolicy Bypass -File build_whdload_queries.ps1 -entriesFiles "data\hd-games\entries\hd-games_entries.csv" -queryPatchesFile "data\hd-games\details\hd-games_detail_query_patches.csv" -queriesFile "data\hd-games\details\hd-games_detail_queries.csv" -addFilteredName -removeQueryWordsPattern "^(Demo|Disk|OCS|ECS|AGA|CDTV|CD32)$"