; Favourites Mode
IF EXISTS ENV:favouritesmode
	execute S:Favourites "ags2" "S" "Scorched Tanks"
	IF $favouritesmode EQ "add"
		SKIP end
	ENDIF
	IF $favouritesmode EQ "remove"
		SKIP end
	ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Start
cd "HD-Games:ScorchedTanks/"
WBRun Scorched_TanksV1.90 SYNC

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end
